const example_data = {
    "style":"style_1",
    "components":{
        "comp_0":{
            "id":"page_comp_1",
            "comp_type":"Headers",
            "style_number":1,
            "values":{
                "component_0_value_1":"h1",
                "component_0_value_2":"h1",
                "component_0_value_3":"h1"
            }
        },
        "comp_1":{
            "id":"page_comp_5",
            "comp_type":"Introductions",
            "style_number":1,
            "values":{
                "component_1_value_1":"i1",
                "component_1_value_2":"i1",
                "component_1_value_3":"i1"
            }
        },
        "comp_2":{
            "id":"page_comp_5_0",
            "comp_type":"Introductions",
            "style_number":1,
            "values":{
                "component_2_value_1":"i2",
                "component_2_value_2":"i2",
                "component_2_value_3":"i2"
            }
        },
        "comp_3":{
            "id":"page_comp_6_0_1",
            "comp_type":"Introductions",
            "style_number":2,
            "values":{
                "component_3_value_1":"i3",
                "component_3_value_2":"i3",
                "component_3_value_3":"i3"
            }
        },
        "comp_4":{
            "id":"page_comp_7_0_1_2_3",
            "comp_type":"Introductions",
            "style_number":3,
            "values":{
                "component_4_value_1":"i4",
                "component_4_value_2":"i4",
                "component_4_value_3":"i4"
            }
        },
        "comp_5":{
            "id":"page_comp_8_0_1_2",
            "comp_type":"Introductions",
            "style_number":4,
            "values":{
                "component_5_value_1":"i5",
                "component_5_value_2":"i5",
                "component_5_value_3":"i5"
            }
        }
    }
}

export default example_data;